# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('town', models.CharField(max_length=200, unique=True)),
                ('locality', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kejatype', models.CharField(max_length=200)),
                ('caretaker', models.CharField(max_length=200)),
                ('caretaker_no', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('toilet_photo', models.ImageField(upload_to=b'')),
                ('kitchen_photo', models.ImageField(upload_to=b'')),
                ('bedroom_photo', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
