# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keja',
            name='id',
        ),
        migrations.AddField(
            model_name='keja',
            name='ona_object_id',
            field=models.IntegerField(default=1212, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
