# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 18:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160930_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keja',
            name='bedroom_photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./media/photos'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='keja',
            name='kitchen_photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./media/photos'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='keja',
            name='toilet_photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./media/photos'), upload_to=b''),
        ),
    ]
