# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:30
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161004_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='keja',
            name='position',
            field=geoposition.fields.GeopositionField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
