# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_keja_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keja',
            old_name='ona_object_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='keja',
            old_name='caretaker',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='keja',
            old_name='caretaker_no',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='keja',
            old_name='kejatype',
            new_name='keja_type',
        ),
        migrations.RenameField(
            model_name='keja',
            old_name='name',
            new_name='rentals_name',
        ),
    ]
